// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8eg7ABUVCO9NezZOUsCcOwD7wcE3v5Fk',
    appId: '1:34796268843:web:1d0b0b689770ccb253696e',
    messagingSenderId: '34796268843',
    projectId: 'loginapp-22b40',
    authDomain: 'loginapp-22b40.firebaseapp.com',
    storageBucket: 'loginapp-22b40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNxur5RDZ6oDVf0v-XrOHU8IGuerOrZ6Y',
    appId: '1:34796268843:android:00f9cff1e09ff7ee53696e',
    messagingSenderId: '34796268843',
    projectId: 'loginapp-22b40',
    storageBucket: 'loginapp-22b40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GV9qdbV7tYTHCd2Ub2t7JYb19E_OrH0',
    appId: '1:34796268843:ios:f917d9792405ef2953696e',
    messagingSenderId: '34796268843',
    projectId: 'loginapp-22b40',
    storageBucket: 'loginapp-22b40.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_GV9qdbV7tYTHCd2Ub2t7JYb19E_OrH0',
    appId: '1:34796268843:ios:f917d9792405ef2953696e',
    messagingSenderId: '34796268843',
    projectId: 'loginapp-22b40',
    storageBucket: 'loginapp-22b40.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8eg7ABUVCO9NezZOUsCcOwD7wcE3v5Fk',
    appId: '1:34796268843:web:44ce4605ee2c402a53696e',
    messagingSenderId: '34796268843',
    projectId: 'loginapp-22b40',
    authDomain: 'loginapp-22b40.firebaseapp.com',
    storageBucket: 'loginapp-22b40.firebasestorage.app',
  );

}